apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  type: NodePort
  ports:
    - name: "10000"
      port: 10000
      targetPort: 80
    - name: "10001"
      port: 10001
      targetPort: 80
    - name: "10002"
      port: 10002
      targetPort: 80
    - name: "10003"
      port: 10003
      targetPort: 80
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}
